apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-bbsn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-bbsn
    app.kubernetes.io/part-of: tkwch-fix-0075-0018-app
  name: devfile-sample-bbsn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-bbsn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-bbsn
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0018-tenant/tkwch-fix-0075-0018-app/devfile-sample-bbsn@sha256:0011079d094874f80878b5da1b5ed169697219357f8220f28adb3f1fab635902
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
